name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Lint
        working-directory: ./web
        run: npm run lint

      - name: Test
        working-directory: ./web
        run: npm run test

      - name: Build
        working-directory: ./web
        run: npm run build

  bot-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: bot/package-lock.json

      - name: Install Dependencies
        working-directory: ./bot
        run: npm ci

      - name: Build
        working-directory: ./bot
        run: npm run build
